image:
  name: hashicorp/terraform:1.10.5
  entrypoint:
    - /usr/bin/env
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# ------------------------------------------------------------------------------
# STAGES
# ------------------------------------------------------------------------------

stages:
  - test

# ------------------------------------------------------------------------------
# JOBS
# ------------------------------------------------------------------------------

fmt:
  stage: test
  script:
    - terraform fmt -check

validate:
  stage: test
  before_script:
    - terraform init -backend=false
  script:
    - terraform validate